frontend/coprs_frontend/coprs/__init__.py
from __future__ import with_statement

import os
import flask

from flask_sqlalchemy import SQLAlchemy
from flask_openid import OpenID
from flask_whooshee import Whooshee
from openid_teams.teams import TeamsResponse

from coprs.redis_session import RedisSessionInterface

app = flask.Flask(__name__)
if "COPRS_ENVIRON_PRODUCTION" in os.environ:
    app.config.from_object("coprs.config.ProductionConfig")
elif "COPRS_ENVIRON_UNITTEST" in os.environ:
    app.config.from_object("coprs.config.UnitTestConfig")
else:
    app.config.from_object("coprs.config.DevelopmentConfig")
if os.environ.get("COPR_CONFIG"):
    app.config.from_envvar("COPR_CONFIG")
else:
    app.config.from_pyfile("/etc/copr/copr.conf", silent=True)


oid = OpenID(
    app, app.config["OPENID_STORE"],
    safe_roots=[],
    extension_responses=[TeamsResponse]
)

db = SQLAlchemy(app)
whooshee = Whooshee(app)


import coprs.filters
import coprs.log
from coprs.log import setup_log
import coprs.models
import coprs.whoosheers

from coprs.helpers import RedisConnectionProvider
rcp = RedisConnectionProvider(config=app.config)
app.session_interface = RedisSessionInterface(rcp.get_connection())

from coprs.views import admin_ns
from coprs.views.admin_ns import admin_general
from coprs.views import api_ns
from coprs.views.api_ns import api_general
from coprs.views import coprs_ns
from coprs.views.coprs_ns import coprs_builds
from coprs.views.coprs_ns import coprs_general
from coprs.views.coprs_ns import coprs_chroots
from coprs.views.coprs_ns import coprs_packages
from coprs.views import backend_ns
from coprs.views.backend_ns import backend_general
from coprs.views import misc
from coprs.views import status_ns
from coprs.views.status_ns import status_general
from coprs.views import recent_ns
from coprs.views.recent_ns import recent_general
from coprs.views.stats_ns import stats_receiver
from coprs.views import tmp_ns
from coprs.views.tmp_ns import tmp_general
from coprs.views.groups_ns import groups_ns
from coprs.views.groups_ns import groups_general
from coprs.views.webhooks_ns import webhooks_ns
from coprs.views.webhooks_ns import webhooks_general


from .context_processors import include_banner, inject_fedmenu

setup_log()

app.register_blueprint(api_ns.api_ns)
app.register_blueprint(admin_ns.admin_ns)
app.register_blueprint(coprs_ns.coprs_ns)
app.register_blueprint(misc.misc)
app.register_blueprint(backend_ns.backend_ns)
app.register_blueprint(status_ns.status_ns)
app.register_blueprint(recent_ns.recent_ns)
app.register_blueprint(stats_receiver.stats_rcv_ns)
app.register_blueprint(tmp_ns.tmp_ns)
app.register_blueprint(groups_ns)
app.register_blueprint(webhooks_ns)

app.add_url_rule("/", "coprs_ns.coprs_show", coprs_general.coprs_show)

app.jinja_env.trim_blocks = True
app.jinja_env.lstrip_blocks = True

from coprs.rest_api import rest_api_bp, register_api_error_handler, URL_PREFIX
register_api_error_handler(app)
app.register_blueprint(rest_api_bp, url_prefix=URL_PREFIX)
# register_api(app, db)

frontend/coprs_frontend/coprs/rest_api/__init__.py
# coding: utf-8
import json
from flask import Response, url_for, Blueprint, make_response
from flask_restful import Resource, Api

from coprs.exceptions import InsufficientRightsException

from coprs.rest_api.exceptions import ApiError
from coprs.rest_api.resources.build import BuildListR, BuildR
from coprs.rest_api.resources.build_task import BuildTaskListR, BuildTaskR
from coprs.rest_api.resources.mock_chroot import MockChrootListR, MockChrootR
from coprs.rest_api.resources.project import ProjectListR, ProjectR
from coprs.rest_api.resources.project_chroot import ProjectChrootListR, ProjectChrootR

URL_PREFIX = "/api_2"


class RootR(Resource):
    @classmethod
    def get(cls):
        return {
            "_links": {
                "self": {"href": url_for(".rootr")},
                "projects": {
                    "href": url_for(".projectlistr"),
                    "query_params": [
                        {
                            "name": u"owner",
                            "type": u"string",
                            "description": u"Select only project owned by the user"
                        }
                    ]
                },
                "mock_chroots": {"href": url_for(".mockchrootlistr")},
                "builds": {"href": url_for(".buildlistr")},
                "build_tasks": {"href": url_for(".buildtasklistr")},
            }
        }


class MyApi(Api):
    # flask-restfull error handling quite buggy right now
    def error_router(self, original_handler, e):
        return original_handler(e)
#     # def handle_error(self, e):
#     #
#     #     if isinstance(e, sqlalchemy.orm.exc.NoResultFound):
#     #         return self.make_response(str(e), 404)
#     #
#     #
#     #     super(MyApi, self).handle_error(e)


# def register_api(app, db):


rest_api_bp = Blueprint("rest_api_bp", __name__)
api = MyApi(rest_api_bp, catch_all_404s=True)

api.add_resource(RootR, "/")
api.add_resource(ProjectListR, "/projects")
api.add_resource(ProjectR, "/projects/<int:project_id>")

api.add_resource(MockChrootListR, "/mock_chroots")
api.add_resource(MockChrootR, "/mock_chroots/<name>")

api.add_resource(BuildListR, "/builds")
api.add_resource(BuildR, "/builds/<int:build_id>")

api.add_resource(ProjectChrootListR, "/projects/<int:project_id>/chroots")
api.add_resource(ProjectChrootR, "/projects/<int:project_id>/chroots/<name>")


api.add_resource(BuildTaskListR, "/build_tasks")
# todo: add redirect from /build_tasks/<int:build_id> -> /build_tasks?build_id=<build_id>
api.add_resource(BuildTaskR, "/build_tasks/<int:build_id>/<name>")


def register_api_error_handler(app):
    @app.errorhandler(ApiError)
    def handle_api_error(error):
        """
        :param ApiError error:
        """

        content = {
            "message": error.msg,
        }
        if error.data:
            content["data"] = error.data

        response = make_response(json.dumps(content), error.code)
        response.headers["Content-Type"] = "application/json"
        return response

frontend/coprs_frontend/coprs/rest_api/resources/__init__.py
# coding: utf-8

frontend/coprs_frontend/coprs/views/admin_ns/__init__.py
import flask

admin_ns = flask.Blueprint("admin_ns", __name__, url_prefix="/admin")

frontend/coprs_frontend/coprs/views/api_ns/__init__.py
import json

import flask
from flask import make_response

from coprs.exceptions import CoprHttpException


api_ns = flask.Blueprint("api_ns", __name__, url_prefix="/api")


def error_response(error):
    """

    :type error: CoprHttpException
    :return:
    """
    body = {
        "error": error.message,
        "output": "notok"
    }
    if error.kwargs:
        body.update(error.kwargs)
    resp = make_response(json.dumps(body), error.code)
    resp.mimetype = "application/json"

    return resp


@api_ns.errorhandler(CoprHttpException)
def handle_api_errors(error):
    return error_response(error)

frontend/coprs_frontend/coprs/views/backend_ns/__init__.py
import flask

backend_ns = flask.Blueprint("backend_ns", __name__, url_prefix="/backend")

frontend/coprs_frontend/coprs/views/coprs_ns/__init__.py
# coding: utf-8

import flask

from coprs.views.misc import page_not_found, access_restricted, bad_request_handler, server_error_handler
from coprs.exceptions import ObjectNotFound, AccessRestricted, BadRequest, CoprHttpException

coprs_ns = flask.Blueprint("coprs_ns", __name__, url_prefix="/coprs")


@coprs_ns.errorhandler(ObjectNotFound)
def handle_404(error):
    return page_not_found(error.message)


@coprs_ns.errorhandler(AccessRestricted)
def handle_403(error):
    return access_restricted(error.message)


@coprs_ns.errorhandler(BadRequest)
def handle_400(error):
    return bad_request_handler(error.message)


@coprs_ns.errorhandler(CoprHttpException)
def handle_500(error):
    return server_error_handler(error.message)

frontend/coprs_frontend/coprs/views/misc.py
import base64
import datetime
import functools
from functools import wraps, partial

from netaddr import IPAddress, IPNetwork
import re
import flask

from openid_teams.teams import TeamsRequest

from coprs import app
from coprs import db
from coprs import helpers
from coprs import models
from coprs import oid
from coprs.logic.complex_logic import ComplexLogic
from coprs.logic.users_logic import UsersLogic
from coprs.logic.coprs_logic import CoprsLogic


def fed_openidize_name(name):
    """
    Create proper Fedora OpenID name from short name.

    >>> fedoraoid == fed_openidize_name(user.name)
    True
    """

    return "http://{0}.id.fedoraproject.org/".format(name)


def create_user_wrapper(username, email, timezone=None):
    expiration_date_token = datetime.date.today() + \
        datetime.timedelta(
            days=flask.current_app.config["API_TOKEN_EXPIRATION"])

    copr64 = base64.b64encode(b"copr") + b"##"
    user = models.User(username=username, mail=email,
                       timezone=timezone,
                       api_login=copr64.decode("utf-8") + helpers.generate_api_token(
                           app.config["API_TOKEN_LENGTH"] - len(copr64)),
                       api_token=helpers.generate_api_token(
                           app.config["API_TOKEN_LENGTH"]),
                       api_token_expiration=expiration_date_token)
    return user


def fed_raw_name(oidname):
    return oidname.replace(".id.fedoraproject.org/", "") \
                  .replace("http://", "")


def krb_strip_realm(fullname):
    return re.sub(r'@.*', '', fullname)


@app.before_request
def set_empty_user():
    flask.g.user = None


@app.before_request
def lookup_current_user():
    flask.g.user = username = None
    if "openid" in flask.session:
        username = fed_raw_name(flask.session["openid"])
    elif "krb5_login" in flask.session:
        username = flask.session["krb5_login"]

    if username:
        flask.g.user = models.User.query.filter(
            models.User.username == username).first()


@app.errorhandler(404)
def page_not_found(message):
    return flask.render_template("404.html", message=message), 404


@app.errorhandler(403)
def access_restricted(message):
    return flask.render_template("403.html", message=message), 403


def generic_error(message, code=500, title=None):
    """
    :type message: str
    :type err: CoprHttpException
    """
    return flask.render_template("_error.html",
                                 message=message,
                                 error_code=code,
                                 error_title=title), code


server_error_handler = partial(generic_error, code=500, title="Internal Server Error")
bad_request_handler = partial(generic_error, code=400, title="Bad Request")

app.errorhandler(500)(server_error_handler)
app.errorhandler(400)(bad_request_handler)

misc = flask.Blueprint("misc", __name__)


@misc.route(app.config['KRB5_LOGIN_BASEURI'] + "<name>/", methods=["GET"])
def krb5_login(name):
    """
    Handle the Kerberos authentication.

    Note that if we are able to get here, either the user is authenticated
    correctly, or apache is mis-configured and it does not perform KRB
    authentication at all.  Note also, even if that can be considered ugly, we
    are reusing oid's get_next_url feature with kerberos login.
    """

    # Already logged in?
    if flask.g.user is not None:
        return flask.redirect(oid.get_next_url())

    krb_config = app.config['KRB5_LOGIN']

    found = None
    for key in krb_config.keys():
        if krb_config[key]['URI'] == name:
            found = key
            break

    if not found:
        # no KRB5_LOGIN.<name> configured in copr.conf
        return flask.render_template("404.html"), 404

    if 'REMOTE_USER' not in flask.request.environ:
        nocred = "Kerberos authentication failed (no credentials provided)"
        return flask.render_template("403.html", message=nocred), 403

    krb_username = flask.request.environ['REMOTE_USER']
    username = krb_strip_realm(krb_username)

    krb_login = (
        models.Krb5Login.query
        .filter(models.Krb5Login.config_name == key)
        .filter(models.Krb5Login.primary == username)
        .first()
    )
    if krb_login:
        flask.g.user = krb_login.user
        flask.session['krb5_login'] = krb_login.user.name
        flask.flash(u"Welcome, {0}".format(flask.g.user.name))
        return flask.redirect(oid.get_next_url())

    # We need to create row in 'krb5_login' table
    user = models.User.query.filter(models.User.username == username).first()
    if not user:
        # Even the item in 'user' table does not exist, create _now_
        email = username + "@" + krb_config[key]['email_domain']
        user = create_user_wrapper(username, email)
        db.session.add(user)

    krb_login = models.Krb5Login(user=user, primary=username, config_name=key)
    db.session.add(krb_login)
    db.session.commit()

    flask.flash(u"Welcome, {0}".format(user.name))
    flask.g.user = user
    flask.session['krb5_login'] = user.name
    return flask.redirect(oid.get_next_url())


@misc.route("/login/", methods=["GET"])
@oid.loginhandler
def login():
    if flask.g.user is not None:
        return flask.redirect(oid.get_next_url())
    else:
        # a bit of magic
        team_req = TeamsRequest(["_FAS_ALL_GROUPS_"])
        return oid.try_login("https://id.fedoraproject.org/",
                             ask_for=["email", "timezone"],
                             extensions=[team_req])


@oid.after_login
def create_or_login(resp):
    flask.session["openid"] = resp.identity_url
    fasusername = resp.identity_url.replace(
        ".id.fedoraproject.org/", "").replace("http://", "")

    # kidding me.. or not
    if fasusername and (
            (
                app.config["USE_ALLOWED_USERS"] and
                fasusername in app.config["ALLOWED_USERS"]
            ) or not app.config["USE_ALLOWED_USERS"]):

        username = fed_raw_name(resp.identity_url)
        user = models.User.query.filter(
            models.User.username == username).first()
        if not user:  # create if not created already
            user = create_user_wrapper(username, resp.email, resp.timezone)
        else:
            user.mail = resp.email
            user.timezone = resp.timezone
        if "lp" in resp.extensions:
            team_resp = resp.extensions['lp']  # name space for the teams extension
            user.openid_groups = {"fas_groups": team_resp.teams}

        db.session.add(user)
        db.session.commit()
        flask.flash(u"Welcome, {0}".format(user.name))
        flask.g.user = user

        if flask.request.url_root == oid.get_next_url():
            return flask.redirect(flask.url_for("coprs_ns.coprs_by_owner",
                                                username=user.name))
        return flask.redirect(oid.get_next_url())
    else:
        flask.flash("User '{0}' is not allowed".format(fasusername))
        return flask.redirect(oid.get_next_url())


@misc.route("/logout/")
def logout():
    flask.session.pop("openid", None)
    flask.session.pop("krb5_login", None)
    flask.flash(u"You were signed out")
    return flask.redirect(oid.get_next_url())


def api_login_required(f):
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        token = None
        apt_login = None
        if "Authorization" in flask.request.headers:
            base64string = flask.request.headers["Authorization"]
            base64string = base64string.split()[1].strip()
            userstring = base64.b64decode(base64string)
            (apt_login, token) = userstring.decode("utf-8").split(":")
        token_auth = False
        if token and apt_login:
            user = UsersLogic.get_by_api_login(apt_login).first()
            if (user and user.api_token == token and
                    user.api_token_expiration >= datetime.date.today()):

                token_auth = True
                flask.g.user = user
        if not token_auth:
            output = {
                "output": "notok",
                "error": "Login invalid/expired. "
                         "Please visit https://copr.fedoraproject.org/api "
                         "get or renew your API token.",
            }
            jsonout = flask.jsonify(output)
            jsonout.status_code = 500
            return jsonout
        return f(*args, **kwargs)
    return decorated_function


def login_required(role=helpers.RoleEnum("user")):
    def view_wrapper(f):
        @functools.wraps(f)
        def decorated_function(*args, **kwargs):
            if flask.g.user is None:
                return flask.redirect(flask.url_for("misc.login",
                                                    next=flask.request.url))

            if role == helpers.RoleEnum("admin") and not flask.g.user.admin:
                flask.flash("You are not allowed to access admin section.")
                return flask.redirect(flask.url_for("coprs_ns.coprs_show"))

            return f(*args, **kwargs)
        return decorated_function
    # hack: if login_required is used without params, the "role" parameter
    # is in fact the decorated function, so we need to return
    # the wrapped function, not the wrapper
    # proper solution would be to use login_required() with parentheses
    # everywhere, even if they"re empty - TODO
    if callable(role):
        return view_wrapper(role)
    else:
        return view_wrapper


# backend authentication
def backend_authenticated(f):
    @functools.wraps(f)
    def decorated_function(*args, **kwargs):
        auth = flask.request.authorization
        if not auth or auth.password != app.config["BACKEND_PASSWORD"]:
            return "You have to provide the correct password\n", 401

        return f(*args, **kwargs)
    return decorated_function


def intranet_required(f):
    @functools.wraps(f)

frontend/coprs_frontend/coprs/templates/_error.html
{% extends "layout.html" %}
{% block title %}Not Found{% endblock %}
{% block header %}Not Found!{% endblock %}
{% block body %}
  <h1> Error {{ error_code }}
  {% if error_title %}
    : {{ error_title }}
  {% endif %}

  </h1>
  {% if message %}
    {{ message }}
  {% else %}
    Something went wrong
  {% endif %}
{% endblock %}

frontend/coprs_frontend/coprs/templates/api.html
{% extends "layout.html" %}
{% block title %}API for Copr{% endblock %}
{% block header %}API for the Copr Build System{% endblock %}
{%block main_menu_api %}active{% endblock %}
{% block breadcrumbs %}
<ol class="breadcrumb">
  <li>
    <a href="{{ url_for('coprs_ns.coprs_show') }}">Home</a>
  </li>
  <li class="active">
    API
  </li>
</ol>
{% endblock %}
{% block body %}
  {% if error %}<p class="error"><strong>Error:</strong> {{ error }}</p>{% endif %}

  <div>
    <h1>Copr API</h1>

    <h2>API Token</h2>
    <p>In order to access the restricted parts of the API, you will need to provide an API token.
    This token is unique, specific to you and <span style="font-weight:bold;">
    should not be shared!</span>.
    </p>

    <p>The API token is valid for {{ config['API_TOKEN_EXPIRATION'] }} days after it has been generated.
    </p>

    {% if g.user %}
    <p>Your information (you can directly paste this into ~/.config/copr):</p>
    <pre style="font-size:120%">
[copr-cli]
login = {{ g.user.api_login }}
username = {{ g.user.name }}
token = {{ g.user.api_token }}
copr_url = {{ ('https://' + config['PUBLIC_COPR_HOSTNAME'])| fix_url_https_frontend}}
# expiration date: {{ g.user.api_token_expiration }}
</pre>

    <a href="{{ url_for('api_ns.api_new_token') }}">
        <input type="button" value="Generate a new token" />
    </a>
    {% else %}
    <p style="font-style:italic">You need to be logged in to see your API token.</p>
    {% endif %}

    <h2>The API</h2>

    <p> Api documentation is available at:
      <a href="http://copr-rest-api.readthedocs.org/en/latest/index.html">
        http://copr-rest-api.readthedocs.org/en/latest/index.html
      </a>
    </p>
  </div>
{% endblock %}

frontend/coprs_frontend/coprs/templates/layout.html
{% from "_helpers.html" import alert %}

<!doctype html>
<html>
<head>
  <title>{% block title %}Coprs Build System{% endblock %}</title>
  <script src="{{ url_for('static', filename='components/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='components/jquery-ui/jquery-ui.min.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='components/jquery-ui/jquery-ui.min.css') }}" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/vnd.microsoft.icon">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
  <link href="{{ url_for('static', filename='css/patternfly.min.css') }}" rel="stylesheet" media="screen, print">
  <link href="{{ url_for('static', filename='css/custom-styles.css') }}" rel="stylesheet" media="screen, print">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="../components/html5shiv/dist/html5shiv.min.js"></script>
  <script src="../components/respond/dest/respond.min.js"></script>
  <![endif]-->
  <!-- IE8 requires jQuery and Bootstrap JS to load in head to prevent rendering bugs -->
  <!-- IE8 requires jQuery v1.x -->
  <script src="{{ url_for('static', filename='components/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='components/datatables/media/js/jquery.dataTables.js') }}"></script>
  <script src="{{ url_for('static', filename='js/patternfly.min.js') }}"></script>

  <script src="{{ url_for('static', filename='copr.js') }}"></script>
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='copr.css') }}">
</head>

<body>
  <!-- BANNER -->
  {% if copr_banner %}
      {{ copr_banner | safe }}
  {% endif  %}

  <!-- MAIN MENU -->
  <nav class="" id="main-bar">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-7 col-xs-6">
          <a href="{{ url_for('coprs_ns.coprs_show') }}">
            <img id="logo" src="{{ url_for('static', filename='copr_logo.png') }}" alt="Copr Build System">
          </a>
        </div>
        <div class="col-md-4 col-sm-5 col-xs-6">
          <div id="login-menu" class="text-right">
          {% if g.user %}
            <a href="https://admin.fedoraproject.org/accounts/user/view/{{ g.user.name }}">{{ g.user.name }}</a> | <a href="{{ url_for('misc.logout') }}">log out</a>
          {% else %}
            <a href="{{ url_for('misc.login') }}">log in</a> |
            {% for key,val in config.KRB5_LOGIN.items() %}
            <a href="{{ config.KRB5_LOGIN_BASEURI }}{{ val.URI }}/">{{ val.log_text }}</a> |
            {% endfor %}
            <a href="https://admin.fedoraproject.org/accounts/user/new">sign up</a>
          {% endif %}
          </div>
          <form role="search" method="get" action="{{ url_for('coprs_ns.coprs_fulltext_search') }}">
            <div class="input-group menu-search">
              <input name="fulltext" type="text" class="form-control" placeholder="Search projects" value="{% block search_box %}{%endblock%}">
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
                </button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  </nav>
  <div class="breadcrumb-panel">
    <div class="container">
        {% block breadcrumbs %}
        {% endblock %}
    </div>
  </div>
  {#
  <nav class="navbar navbar-sm navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="{%block main_menu_projects %}{% endblock %}">
          <a href="{{ url_for('coprs_ns.coprs_show') }}">Projects</a>
        </li>
        <li class="{%block main_menu_status %}{% endblock %}">
          <a href="{{url_for('status_ns.waiting')}}">Status</a>
        </li>
        <li class="{%block main_menu_api %}{% endblock %}">
          <a href="{{ url_for('api_ns.api_home') }}">API</a>
        </li>
      </ul>
    </div>
  </nav>
  #}

  <!-- CONTENT -->
  <div id=content>
    <div class="container">

      <!-- Flash messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% for type, message in messages %}
          {{ alert(message, type) }}
        {% endfor %}
      {% endwith %}

      <!-- the actual content -->
      {% block body %}{% endblock %}

    </div>
    <footer class="footer">
      <div>
        <div class="container text-muted">
          <div class="">
            <div class="row">
              <div class="col-sm-4">
                <dl>
                  <dt><h3>Copr Project</h3></dt>
                  <dd>
                    <ul class="list-unstyled">
                      <li><a href="https://fedorahosted.org/copr/">Project Homepage</a></li>
                      <li><a href="https://fedorahosted.org/copr/wiki/UserDocs">User Documentation</a></li>
                      <li><a href="https://bugzilla.redhat.com/enter_bug.cgi?product=Copr">Report a Bug</a></li>
                      <li><a href="https://fedorahosted.org/copr/wiki/UserDocs#FAQ">FAQ</a></li>
                    </ul>
                  </dd>
                </dl>
              </div>
              <div class="col-sm-4">
                <dl>
                  <dt><h3>Site Navigation</h3></dt>
                  <dd>
                    <ul class="list-unstyled">
                      <li> <a href="{{ url_for('coprs_ns.coprs_show') }}">Home</a> </li>
                      <li> <a href="{{url_for('status_ns.importing')}}">Task Queue</a> </li>
                      <li> <a href="{{ url_for('api_ns.api_home') }}">API</a> </li>
                    </ul>
                  </dd>
                </dl>
              </div>
              <div class="col-sm-4">
                <dl>
                  <dt><h3>Powered by</h3></dt>
                  <dd>
                    <ul class="list-unstyled">
                      <li><a href="https://www.python.org">Python</a></li>
                      <li><a href="http://www.openstack.org">OpenStack</a></li>
                      <li><a href="https://www.patternfly.org">PatternFly</a></li>
                      <li><a href="https://github.com/release-engineering/dist-git">Dist Git</a></li>
                    </ul>
                  </dd>
                </dl>
              </div>
            </div>
            <!-- <small class="text-muted">
              Build __RPM_BUILD_VERSION
            </small> -->
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- FEDORA MENU -->
  {% if fedmenu_url is defined %}
  <script src="{{fedmenu_url}}/js/fedora-libravatar.js"></script>
  <script src="{{fedmenu_url}}/js/fedmenu.js"></script>
  <script>
    fedmenu({
        'url': '{{fedmenu_data_url}}',
        'mimeType': 'application/javascript',
        'position': 'bottom-right',
        {% if copr is defined %}
        'user': '{{copr.owner.name}}',
        {% endif %}
    });
  </script>
  {% endif %}
</body>
</html>

frontend/coprs_frontend/coprs/templates/login.html
{% extends "layout.html" %}
{% block title %}Sign in Coprs{% endblock %}
{% block header %}Sign in Coprs Build System{% endblock %}
{% block body %}
  {% if error %}<p class="error"><strong>Error:</strong> {{ error }}</p>{% endif %}

  <div>
    <h2>Fedora Accounts System login</h2>
    <form action="" method="post">
      Username:
      <input type="text" name="fasuname" size="16" class="fas">
      <input type="submit" value="Sign in">
      <input type="hidden" name="next" value="{{ next }}">
    </form>
  </div>
{% endblock %}